Repository javascript-tutorial/pl.javascript.info, pull requests merged in 2019-10, with the labels that each got.

#19 Update glossary - new section, new translations
  GLOSSARY.md
Labels: review needed

#17 Intro
  1-js/01-getting-started/1-intro/article.md
  GLOSSARY.md
Labels: needs +1

#28 Translate 'Variables' page
  1-js/02-first-steps/04-variables/1-hello-variables/solution.md
  1-js/02-first-steps/04-variables/1-hello-variables/task.md
  1-js/02-first-steps/04-variables/2-declare-variables/solution.md
  1-js/02-first-steps/04-variables/2-declare-variables/task.md
  1-js/02-first-steps/04-variables/3-uppercast-constant/solution.md
  1-js/02-first-steps/04-variables/3-uppercast-constant/task.md
  1-js/02-first-steps/04-variables/article.md
  1-js/02-first-steps/04-variables/variable-change.svg
  1-js/02-first-steps/04-variables/variable.svg
Labels: review needed

#26 Comments
  1-js/03-code-quality/03-comments/article.md
Labels: needs +1

#29 Translate 'Data types' page
  1-js/02-first-steps/05-types/1-string-quotes/solution.md
  1-js/02-first-steps/05-types/1-string-quotes/task.md
  1-js/02-first-steps/05-types/article.md
Labels: ready to merge

#30 Translate 'Type conversions' page
  1-js/02-first-steps/06-type-conversions/1-primitive-conversions-questions/solution.md
  1-js/02-first-steps/06-type-conversions/1-primitive-conversions-questions/task.md
  1-js/02-first-steps/06-type-conversions/article.md
  1-js/02-first-steps/08-comparison/article.md
Labels: ready to merge

#22 Fetch
  5-network/01-fetch/01-fetch-users/_js.view/source.js
  5-network/01-fetch/01-fetch-users/_js.view/test.js
  5-network/01-fetch/01-fetch-users/solution.md
  5-network/01-fetch/01-fetch-users/task.md
  5-network/01-fetch/article.md
  5-network/01-fetch/post.view/server.js
  5-network/02-formdata/article.md
  5-network/02-formdata/post.view/server.js
Labels: needs +1

#31 Fetch: Download progress
  5-network/03-fetch-progress/article.md
  5-network/03-fetch-progress/progress.view/index.html
Labels: needs +1

#32 Translate 'Operators' page
  1-js/02-first-steps/07-operators/1-increment-order/solution.md
  1-js/02-first-steps/07-operators/1-increment-order/task.md
  1-js/02-first-steps/07-operators/2-assignment-result/solution.md
  1-js/02-first-steps/07-operators/2-assignment-result/task.md
  1-js/02-first-steps/07-operators/article.md
Labels: needs +1
